apiVersion: v1
kind: Service
metadata:
  name: nats-lb
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "10"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: nats
  ports:
    - protocol: TCP
      port: 4222
      targetPort: 4222
      name: client
    - protocol: TCP
      port: 7422
      targetPort: 7422
      name: leafnodes
